### ISSUE TITLE
Alert: implementation

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1026]
https://facebook.github.io/react-native/docs/alert

**Comment by piranna** [comment]
https://github.com/piranna/react-native-web-extended/blob/master/src/apis/Alert/index.js

**Comment by RichardLindhout** [comment]
For now I do something like this to workaround this issue.

```
const alertTitle = 'Foutmelding'
const alertText = 'Geen toegang tot locatiedata'
if (Platform.OS === 'web') {
   alert(alertText)
} else {
    Alert.alert(alertTitle, alertText)
}
```

**Comment by piranna** [comment]
Browser `alert()` is blocking, so it's not recomended to use. Not sure why it's not deprecated yet...

**Comment by vlimag** [comment]
Does react-native-web supports Alert already?

**Comment by steida** [comment]
@vlimag Check readme https://github.com/necolas/react-native-web#modules

**Comment by arqex** [comment]
What do you think about implementing it using react portals? We can inject the node in the dom and use a portal to show/hide.

We can ship simple styling for it and create a way to let the developer customize the appearance and the appearing/hiding transition.

**Comment by vlimag** [comment]
What I've done so far.
one file for default react native alert, and one file for react web alert.
Alert. js
```
import { Alert } from 'react-native'

export const StdAlert = (title, desc, onPress = () => { }) => {
  Alert.alert(
    title,
    desc,
    [
      { text: 'OK', onPress: () => onPress() }
    ],
    { cancelable: false }
  )
}

export const BinaryAlert = (title, desc, onPositivePress = () => { }, onNegativePress = () => { }) => {
  Alert.alert(
    title,
    desc,
    [
      { text: 'Sim', onPress: () => onPositivePress() },
      { text: 'Não', onPress: () => onNegativePress() }
    ],
    { cancelable: false }
  )
}
```

and for web, Alert.web.js


```
export const StdAlert = (title, desc, onPress = () => { }) => {
  alert(`${title}\n${desc}`)
  if (onPress) onPress()
}

export const BinaryAlert = (title, desc, onPositivePress = () => { }, onNegativePress = () => { }) => {
  const res = window.confirm(`${title}\n${desc}`)
  if (res) onPositivePress()
  else onNegativePress()
}
```
Then you use it as following:

```


```

**Comment by joan-saum** [comment]
@vlimag , how about dependencies which use the Alert from react native ? (#1366)

**Comment by vlimag** [comment]
@joan-saum As a provisory solution you should probably fork the dependency, change as necessary - following the example above - and publish to npm to use it.
Hopefully React native alert will be available at some time on React Native Web

**Comment by tonypee** [comment]
I just created my own alert popup for web, using native-base - works pretty well 

https://gist.github.com/tonypee/f3ebb3a6f89e6d73255a5823092b24c6

it needs to be instantiated in the root of the app too

**Comment by joshbalfour** [comment]
_very_ quick and dirty polyfill I whipped up if anyone else got super stuck by this:

```js
import { Alert, Platform } from 'react-native'

const alertPolyfill = (title, description, options, extra) => {
    const result = window.confirm([title, description].filter(Boolean).join('\n'))

    if (result) {
        const confirmOption = options.find(({ style }) => style !== 'cancel')
        confirmOption && confirmOption.onPress()
    } else {
        const cancelOption = options.find(({ style }) => style === 'cancel')
        cancelOption && cancelOption.onPress()
    }
}

const alert = Platform.OS === 'web' ? alertPolyfill : Alert.alert

export default alert
```

**Comment by benceg** [comment]
Thank you @joshbalfour.

Here's roughly the same in TypeScript for those who need it. Written as a singleton in order to be able to implement `AlertStatic` symmetrically from React Native.

```ts
// Alert.web.ts
import { AlertButton, AlertStatic } from 'react-native';

class WebAlert implements Pick<AlertStatic, 'alert'> {
  public alert(title: string, message?: string, buttons?: AlertButton[]): void {
    if (buttons === undefined || buttons.length === 0) {
      window.alert([title, message].filter(Boolean).join('\n'));
      return;
    }

    const result = window.confirm([title, message].filter(Boolean).join('\n'));

    if (result === true) {
      const confirm = buttons.find(({ style }) => style !== 'cancel');
      confirm?.onPress?.();
      return;
    }

    const cancel = buttons.find(({ style }) => style === 'cancel');
    cancel?.onPress?.();
  }
}

export const Alert = new WebAlert();
```

Several things to note:
1. Providing no `buttons` argument manifests a basic alert. Providing `buttons` presents a dialogue.
2. The fourth `options` argument is not implemented as it pertains to Android cancellation behaviour only, which has no browser analogue.
3. The `AlertStatic` interface implies an additional `prompt` method, but the React Native docs imply that it hasn't yet been implemented (or that it's just undocumented, for now).

**Comment by blueturtle13g** [comment]
> Browser `alert()` is blocking, so it's not recomended to use. Not sure why it's not deprecated yet...

It's meant to block on purpose!

**Comment by RichardLindhout** [comment]
The Modal PR is merged in react-native-web, that means the Alert implementation will be a lot easier to implement. I'll see if I can find some time to make a PR for this

**Comment by RichardLindhout** [comment]
I just did an experiment with the Modal in the canary version to implement a the Alert API on the web: https://codesandbox.io/s/alert-implementation-z4eoq?file=/src/App.js.
This would require the React DOM to be available before Alert.alert can be called.

I'm not sure how we could handle this better
![ezgif-5-b66429171338](https://user-images.githubusercontent.com/6492229/94273550-dc790880-ff44-11ea-8e7d-3ae6ab3f3d5a.gif)

@necolas Is it a requirement of the web version of the Alert.api to be available before React is mounted?

**Comment by necolas** [comment]
Before React is mounted? What does that mean?

**Comment by RichardLindhout** [comment]
In my implementation the <AlertRoot /> would have to be included somewhere in the three, I don't know if that's possible in the AppRegistry.

So if you would could Alert.alert() before the <AlertRoot /> has rendered it would fail, I presume we should implement the Alert.alert outside of the component tree but that would be hard since <Modal> would not be available.

**Comment by RichardLindhout** [comment]
I think I can workaround the issue I described above, but is it possible to add extra components in the root of a react-native-web app, like an <AlertRoot /> or extra Context providers?

**Comment by RichardLindhout** [comment]
I now have rewritten the Alert proposal to add support for Alerts outside components. 
https://codesandbox.io/s/alert-implementation-z4eoq?file=/src/Alert.js

**Comment by RichardLindhout** [comment]
Do you think the Codesandbox will be good enough for a PR if I 
- add AlertRoot to here: https://github.com/necolas/react-native-web/blob/e4ed0fd3c863e6c61aa3ea8afeff79b7fa74b461/packages/react-native-web/src/exports/AppRegistry/AppContainer.js#L67
- Use Pressable instead of the `<Button />`
- Follow Material Design guidelines for the Alert modal
- Implement all the things Alert has on both platforms

**Comment by itsarnavsingh** [comment]
I went with, https://callstack.github.io/react-native-paper/dialog.html It looks pretty

**Comment by wezzy** [comment]
I've created a fake component using SweetAlert2. It's not perfect and not a complete solution, I've created it for a specific project that I'm porting to web using Expo but it works:

`import Swal from 'sweetalert2';
import {MAIN_COLOR} from "../../styles/colors";

const Alert = {

    alert: (title, description, options) => {

        const alertOptions = {
            title: title,
            text:  description,
            icon:  "info",
        };

        if (title.toLowerCase() === "warning") alertOptions.icon = "warning";
        if (title.toLowerCase() === "error") alertOptions.icon = "error";

        if (options) {
            if (options.length === 1) {

                alertOptions.confirmButtonText = options[0].text;
                alertOptions.showConfirmButton = true;

            } else if (options.length === 2) {

                alertOptions.confirmButtonText = options[0].text;
                alertOptions.showConfirmButton = true;

                alertOptions.cancelButtonText = options[1].text;
                alertOptions.showCancelButton = true;

            } else if (options.length === 3) {

                alertOptions.confirmButtonText = options[0].text;
                alertOptions.showConfirmButton = true;

                alertOptions.cancelButtonText = options[1].text;
                alertOptions.showCancelButton = true;

                alertOptions.denyButtonText = options[2].text;
                alertOptions.showDenyButton = true;

            }
        }

        alertOptions.confirmButtonColor = MAIN_COLOR;
        alertOptions.cancelButtonColor  = MAIN_COLOR;
        alertOptions.denyButtonColor    = MAIN_COLOR;


        Swal.fire(alertOptions).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {

                if (options.length > 0 && options[0].onPress) options[0].onPress()

            } else if (result.isDismissed) {

                if (options.length > 1 && options[1].onPress) options[1].onPress()

            } else if (result.isDenied) {

                if (options.length > 2 && options[2].onPress) options[2].onPress()

            }
        });

    }
}

export default Alert;
`

**Comment by necolas** [comment]
@RichardLindhout yeah something like that would be a good start

**Comment by kevinrodriguez-io** [comment]
> Do you think the Codesandbox will be good enough for a PR if I
> 
> * add AlertRoot to here: https://github.com/necolas/react-native-web/blob/e4ed0fd3c863e6c61aa3ea8afeff79b7fa74b461/packages/react-native-web/src/exports/AppRegistry/AppContainer.js#L67
> * Use Pressable instead of the `<Button />`
> * Follow Material Design guidelines for the Alert modal
> * Implement all the things Alert has on both platforms

I hate materialways design. It's like a plague, I think that at least, we should be able to modify it.

**Comment by ezekiel747** [comment]
Hi, is there any update on this?
Would love to see a web version for the Alert.alert / .prompt in the same imperative approach.

**Comment by zhigang1992** [comment]
@ezekiel747 there is react-native-paper-alerts that looks pretty good on web.

**Comment by mikehardy** [comment]
@zhigang1992 react-native-paper-alerts is a reasonable solution, thanks for that pointer. I just looked it over and went ahead with an integration of it in https://github.com/invertase/react-native-firebase-authentication-example 

If you're not using react-native-paper then it probably isn't attractive, but if you are - definitely worth a look - mind the styles applied in public/index.html to avoid a keyboard hiding issue if you use prompts with TextInput in the Alerts, but if you're just doing text and buttons, zero issues.

**Comment by p4bl1t0** [comment]
hi there! is there any update on this?

can I help on something? are there any pull request with this working progress?

**Comment by pjk5** [comment]
While not an actual solution for this issue, I was able to make React Native's _Alert_ work on multiple platforms by utilizing the [sweetalert2](https://sweetalert2.github.io/) library for the web.

I've included my code below for anyone who might find it useful. Native Alert API is called for the native platforms and the code falls back to sweetalert2 for the web. The API is almost identical to the native Alert, with one addition to the _AlertButton_ type to enable button type props for sweetalert2.

It seems that the _prompt_ method could also be implemented with sweetalert2 quite easily, but I didn't have the need for that yet.

You can test it out on [Snack](https://snack.expo.dev/CVFHZ-mJx).

------

Install sweetalert2:
```npm install sweetalert2```

Alert.web.ts:
```
import {
  type AlertType,
  type AlertButton,
  type AlertOptions,
} from 'react-native'

import Swal from 'sweetalert2'

export type CustomAlertButton = AlertButton & {
  swalType?: 'deny' | 'cancel' | 'confirm'
}

class Alert {
  static alert(
    title: string,
    message?: string,
    buttons?: CustomAlertButton[],
    options?: AlertOptions
  ): void {
    const confirmButton = buttons
      ? buttons.find((button) => button.swalType === 'confirm')
      : undefined
    const denyButton = buttons
      ? buttons.find((button) => button.swalType === 'deny')
      : undefined
    const cancelButton = buttons
      ? buttons.find((button) => button.swalType === 'cancel')
      : undefined

    Swal.fire({
      title: title,
      text: message,
      showConfirmButton: !!confirmButton,
      showDenyButton: !!denyButton,
      showCancelButton: !!cancelButton,
      confirmButtonText: confirmButton?.text,
      denyButtonText: denyButton?.text,
      cancelButtonText: cancelButton?.text,
    }).then((result) => {
      if (result.isConfirmed) {
        if (confirmButton?.onPress !== undefined) {
          confirmButton.onPress()
        }
      } else if (result.isDenied) {
        if (denyButton?.onPress !== undefined) {
          denyButton.onPress()
        }
      } else if (result.isDismissed) {
        if (cancelButton?.onPress !== undefined) {
          cancelButton.onPress()
        }
      }
    })
  }

  static prompt(
    title: string,
    message?: string,
    callbackOrButtons?: ((text: string) => void) | CustomAlertButton[],
    type?: AlertType,
    defaultValue?: string,
    keyboardType?: string
  ): void {
    throw new Error('Not implemented.')
  }
}

export default Alert
```

Alert.ts
```
import {
  Alert as RNAlert,
  type AlertOptions,
  type AlertButton,
  type AlertType,
} from 'react-native'

type CustomAlertButton = AlertButton & {
  swalType?: 'deny' | 'cancel' | 'confirm'
}

export interface ExtendedAlertStatic {
  alert: (
    title: string,
    message?: string,
    buttons?: CustomAlertButton[],
    options?: AlertOptions
  ) => void
  prompt: (
    title: string,
    message?: string,
    callbackOrButtons?: ((text: string) => void) | CustomAlertButton[],
    type?: AlertType,
    defaultValue?: string,
    keyboardType?: string
  ) => void
}

const Alert: ExtendedAlertStatic = RNAlert as ExtendedAlertStatic

export default Alert
```

**Comment by mensonones** [comment]
I'm creating a multiplatform. simple for now

https://github.com/mensonones/AnywhereAlertConfirm

**Comment by a-eid** [comment]
any updates on this ?

**Comment by a-eid** [comment]
> @a-eid I don't see a PR from you or others, so, no?
> 
> 
> 
> Reading the comments, there is maintainer support for a PR if this affects you:
> 
> 
> 
> https://github.com/necolas/react-native-web/issues/1026#issuecomment-735987062
> 
> 
> 
> Until then, people waiting for the PR fairy to show up or just hoping for an update because hey why not ask, it's just extra unwanted notification traffic for everyone in an open source context. Don't do that 🙏 
> 
> 
> 
> https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

happy to contribute a PR, I am however not sure how this could be handled properly.

**Comment by kevinrodriguez-io** [comment]
Best solution I've found if you want to notify in a non-blocking way is to just use a toast library

**Comment by btoo** [comment]
[tamagui](https://github.com/tamagui/tamagui) has a
> [React Native API Compatible Alert](https://tamagui.dev/bento/elements/dialogs#Alert)

but you have to pay for it

**Comment by blazejkustra** [comment]
The [\<dialog\> ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)element is now widely supported by modern browsers, and it seems like a good fit for implementing the Alert API for React Native Web 😄 

I’ve created a working implementation that mirrors the React Native API (`Alert.alert()` and `Alert.prompt()`) and uses `<dialog>` for native modal behavior. It supports animations and prefers-color-scheme for light/dark mode.


@necolas I’d be happy to raise a PR for this approach! Let me know what you think.

Initial implementation:
```js
function createDialogElement(title, message, buttons, inputField = null) {
  const dialog = document.createElement('dialog');
  dialog.className = 'alert-dialog';
  dialog.innerHTML = `
      <div class="alert-container">
        <div class="alert-text-container">
          <h1 class="alert-header">${title}</h1>
          ${
            inputField || message
              ? `<div class="alert-body">
            ${message ? `<p class="alert-message">${message}</p>` : ''}
            ${inputField ? inputField : ''}
          </div>`
              : ''
          }
        </div>
        <div class="alert-footer" id="buttons"></div>
      </div>
  `;

  const buttonsContainer = dialog.querySelector('#buttons');
  buttons.forEach(({ text, style, onPress }) => {
    const button = document.createElement('button');
    button.innerText = text;
    button.className = style === 'destructive' ? 'alert-btn-destructive' : 'alert-btn-default';
    button.addEventListener('click', () => {
      dialog.close();
      if (onPress) {
        onPress(inputField ? dialog.querySelector('input').value : undefined);
      }
    });
    buttonsContainer.appendChild(button);
  });

  // If there are exactly two buttons, set confirm style
  if (buttons.length === 2) {
    dialog.classList.add('alert-confirm');
  }

  return dialog;
}

class Alert {
  static alert(title, message, buttons = [{ text: 'OK', style: 'default' }]) {
    const dialog = createDialogElement(title, message, buttons);
    document.body.appendChild(dialog);
    dialog.showModal();
    dialog.addEventListener('close', () => {
      document.body.removeChild(dialog);
    });
  }

  static prompt(
    title,
    message,
    buttons = [{ text: 'OK', style: 'default', onPress: () => undefined }],
    inputType = 'plain-text',
    defaultValue = '',
  ) {
    const inputField = `
      <input type="${inputType === 'secure-text' ? 'password' : 'text'}" value="${defaultValue}" class="alert-input" />
    `;
    const dialog = createDialogElement(title, message, buttons, inputField);
    document.body.appendChild(dialog);
    dialog.showModal();
    dialog.addEventListener('close', () => {
      document.body.removeChild(dialog);
    });
  }
}

export default Alert;
```

How it looks unstyled:

<img width="873" alt="image" src="https://github.com/user-attachments/assets/7f6fadfe-6203-4baa-9775-239538585f6f" />

<img width="665" alt="image" src="https://github.com/user-attachments/assets/4939e4f2-21ab-4127-83d9-bf9f292d24ef" />

**Comment by blazejkustra** [comment]
With some CSS tweaks, you can create fully accessible modals that closely mimic the iOS look and feel 🚀 

<img width="411" alt="image" src="https://github.com/user-attachments/assets/71236dc4-b00f-40ee-ae88-81bc0c55d50d" />

<img width="370" alt="image" src="https://github.com/user-attachments/assets/11cd5e15-fded-4841-987c-7db135c7edcf" />

<details>
<summary>CSS for the above</summary>

```css
@keyframes fadeInScale {
  0% {
    opacity: 0;
    transform: scale(1.05);
  }
  100% {
    opacity: 1;
    transform: scale(1);
  }
}

.alert-dialog {
  font-family: 'Inter', sans-serif;
  max-width: 240px;
  background-color: #F9F9F9;
  color: #000; 
  border-radius: 16px;
  padding: 0;
  border: 0;
  animation: fadeInScale 0.3s ease-out;
}

.alert-text-container {
  margin: 20px;
}

.alert-header {
  font-size: 16px;
  text-align: center;
  margin: 0;
}

.alert-body {
  font-size: 14px;
  line-height: 18px;
  text-align: center;
  word-wrap: break-word;
}

.alert-message h1 {
  margin: 0px;
  font-size: 14px;
  line-height: 18px;
}

.alert-footer {
  display: flex;
  flex-direction: row;
  border-top: 0.5px solid #AFAFAE;
}

.alert-footer button {
  padding: 12px;
  width: 100%;
  background: none;
  border: none;
  outline: none;
  color: #007AFF;
  cursor: pointer;
  font-size: 16px;
}

.alert-footer button:focus {
  background-color: #E7E7E7;
}

.alert-footer button.alert-btn-destructive {
  color: #FF3B30;
}

.alert-footer button:hover {
  background-color: #E7E7E7;
}

.alert-confirm .alert-footer button {
  display: inline-block;
}

.alert-footer:has(> button:nth-of-type(2)) button:first-of-type {
  border-right: 0.5px solid #ADAEAD;
}

.alert-input {
  width: 90%;
  padding: 6px;
  font-size: 14px;
  background-color: #FFF;
  color: #000;
  border: 0.5px solid #ADAEAD;
  border-radius: 8px;
  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
  outline: none;
  transition: border-color 0.3s ease, box-shadow 0.3s ease;
}

.alert-input:focus {
  border-color: #007AFF;
  box-shadow: 0 0 5px rgba(0, 122, 255, 0.3);
}

/* Dark Theme */
@media (prefers-color-scheme: dark) {
  .alert-dialog {
    background-color: #3E3E3E;
    color: #FFF; 
  }

  .alert-footer {
    border-top: 0.5px solid #767676;
  }

  .alert-footer button {
    color: #0A84FF;
  }

  .alert-footer button.alert-btn-destructive {
    color: #FF453A;
  }

  .alert-footer button:focus {
    background-color: #5B595A;
  }

  .alert-footer button:hover {
    background-color: #5B595A;
  }

  .alert-footer:has(> button:nth-of-type(2)) button:first-of-type {
    border-right: 0.5px solid #767676;
  }

  .alert-input {
    background-color: #1C1C1E;
    color: #FFF;
    border: 0.5px solid #767676;
    box-shadow: inset 0 1px 2px rgba(255, 255, 255, 0.1);
  }

  .alert-input:focus {
    border-color: #0A84FF;
    box-shadow: 0 0 5px rgba(10, 132, 255, 0.5);
  }
}
```


  
</details>
