### ISSUE TITLE
View Style default value  z-index: 0  Cause child z-index to be invalid

### ISSUE THREAD

**Issue by ickeep** [necolas/react-native-web#1065]
**The problem**

[#689](https://github.com/necolas/react-native-web/issues/689)
View Style default value  z-index: 0  Cause child z-index to be invalid
E.g:
The contents of the FlatList's ListHeaderComponent and renderItem are obscured by the ListFooterComponent

Temporary solution

```js
<View className="clear-flat-list-z-index" style={Style.wp}>
    <FlatList></FlatList>
</View>
```

``` css
.clear-flat-list-z-index > div > div > div > div {
    z-index: auto !important;
}
```

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): ^0.8.9
* React (version): 16.3.0
* Browser: Chrome 68.0.3440.84
