### ISSUE TITLE
Cannot read property 'rules' of undefined (broken in 0.11)

### ISSUE THREAD

**Issue by pcmaffey** [necolas/react-native-web#1430]
**The problem**
RNW *should* work with a snapshot tool like react-snap, that simply renders pages in a broweser (puppeteer) to create static html files before hydrating them. However...

```
Uncaught TypeError: Cannot read property 'rules' of undefined
    at createOrderedCSSStyleSheet.js:49
```

**How to reproduce**
Here's a repro: https://github.com/pcmaffey/rnw-snapshot

It's a create-react-app using react-native-web components. It runs react-snap `postbuild`. Works fine in dev, errors when running the build. 

Can see the error live here: https://objective-bell-dff10b.netlify.com/ 
Or run `serve -s build` locally.

Also to note: this is using v0.11.7. I downgraded to 0.10.1 and it worked. So possibly related to https://github.com/necolas/react-native-web/issues/1286?

**Comment by daaain** [comment]
I had the same problem, apparently this is fixed in `styled-components` v5, at least switching to `"styled-components": "5.0.0-beta.9"` with `"react-native-web": "0.11.7"` seems to work.`

**Comment by necolas** [comment]
This looks like you're running a different version of RNW on the client to what was run on the server, otherwise the inline CSS would be of the expected form.

**Comment by pcmaffey** [comment]
It's definitely the same version of RNW, as react-snap just runs the client code through puppetteer to generate the static files. There is no server...

**Comment by necolas** [comment]
This is the CSS in the head of https://objective-bell-dff10b.netlify.com/

```css
html{text-size-adjust:100%;-webkit-tap-highlight-color:transparent}
body{margin:0}
input::-webkit-inner-spin-button,input::-webkit-outer-spin-button,input::-webkit-search-cancel-button,input::-webkit-search-decoration,input::-webkit-search-results-button,input::-webkit-search-results-decoration{display:none}
:focus:not([data-focusvisible-polyfill]){outline:0}
.css-1dbjc4n{-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-orient:vertical;align-items:stretch;border:0 solid #000;box-sizing:border-box;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;margin:0;min-height:0;min-width:0;padding:0;position:relative;z-index:0}
.css-901oao{border:0 solid #000;box-sizing:border-box;color:#000;display:inline;font:14px system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Ubuntu,"Helvetica Neue",sans-serif;margin:0;padding:0;white-space:pre-wrap;overflow-wrap:break-word}
```

This is the CSS in the RNW snapshots tests:

https://github.com/necolas/react-native-web/blob/9cbe387d9ff8f05c2ebcd332ebf65d8d147c126e/packages/react-native-web/src/exports/AppRegistry/__tests__/__snapshots__/index-test.js.snap#L4-L17

Not only are all the group marker rules missing but selectors like `.css-1dbjc4n` aren't what the library currently produces, e.g., `.css-view-1dbjc4n`
