### ISSUE TITLE
Support autofill styles in webkit browser

### ISSUE THREAD

**Issue by hyochan** [necolas/react-native-web#1896]
**Is your feature request related to a problem? Please describe.**

I've tried to find a way to style `autocomplete` style in `TextInput` and couldn't find any resource about it.

![7ssMpmLIRV](https://user-images.githubusercontent.com/27461460/107031853-34c6ed80-67f6-11eb-9b52-186644f36ce8.gif)

In, dark mode it looks a bit ugly so I wanted to know how to customize this.

In `react`, we could control these styles [followed by the article](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/).

**Describe a solution you'd like**

I'd like to extract extra styles just for the web to handle this instead of putting it in `style` props which are not official types in `react-native`. `webKitAutoFillStyle` would be great.

**Comment by necolas** [comment]
Please can you fork this template and create a test case for the request that demonstrates what is shown in the gif? https://codesandbox.io/s/6lx6ql1w5r

**Comment by necolas** [comment]
I'd rather remove the webkit-specific styles the browser is adding instead of exposing them to user-space

**Comment by necolas** [comment]
Something like this is needed to override the UA styles:

```css
input {
  --bg: lightblue;
  --fs: 16px;
  font-size: var(--fs);
  background-color: var(--bg);
}

input:-webkit-autofill {
  -webkit-box-shadow: 0 0 0 1000px var(--bg) inset;
}

input:-webkit-autofill::first-line {
  font-size: var(--fs);
}
```
