### ISSUE TITLE
Support for showsHorizontalScrollIndicator and showsVerticalScrollIndicator in ScrollView

### ISSUE THREAD

**Issue by Sharcoux** [necolas/react-native-web#1923]
**Is your feature request related to a problem? Please describe.**

This is the [doc](https://reactnative.dev/docs/scrollview#showshorizontalscrollindicator) relative to the feature

**Describe a solution you'd like**

When receiving this prop, we should probably inject the following style:

```css
 /* Hide scrollbar for Chrome, Safari and Opera */
.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.example {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
} 
```

This [this](https://www.w3schools.com/howto/howto_css_hide_scrollbars.asp) for reference

**Describe alternatives you've considered**

 Well, the first solution seems straightforward, but there i always the solution to do:
 
 ```jsx
<Wrapper style={{ overflowX: 'hidden' }}>
  <View style={{ marginRight: -16 }}>
```

**Additional context**
