### ISSUE TITLE
Missing css in SSR

### ISSUE THREAD

**Issue by vivex** [necolas/react-native-web#1983]
**The problem**
Stylesheet generated using `getStyleElement` does not contain some classes which are there in html generated by `ReactDOMServer.renderToString`  (SSR) using rnw components.

Following is the css generated by rnw

```css
html{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;-webkit-tap-highlight-color:rgba(0,0,0,0);}
body{margin:0;}
button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0;}
input::-webkit-inner-spin-button,input::-webkit-outer-spin-button,input::-webkit-search-cancel-button,input::-webkit-search-decoration,input::-webkit-search-results-button,input::-webkit-search-results-decoration{display:none;}
[stylesheet-group="0.1"]{}
:focus:not([data-focusvisible-polyfill]){outline: none;}
[stylesheet-group="1"]{}
.css-view-1dbjc4n{-ms-flex-align:stretch;-ms-flex-direction:column;-ms-flex-negative:0;-ms-flex-preferred-size:auto;-webkit-align-items:stretch;-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-orient:vertical;-webkit-flex-basis:auto;-webkit-flex-direction:column;-webkit-flex-shrink:0;align-items:stretch;border:0 solid black;box-sizing:border-box;display:-webkit-box;display:-moz-box;display:-ms-flexbox;display:-webkit-flex;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;z-index:0;}
[stylesheet-group="2"]{}
.r-flex-13awgt0{-ms-flex:1 1 0%;-webkit-flex:1;flex:1;}
.r-overflow-1udh08x{overflow-x:hidden;overflow-y:hidden;}
[stylesheet-group="2.2"]{}
.r-pointerEvents-12vffkv>*{pointer-events:auto;}
.r-pointerEvents-12vffkv{pointer-events:none!important;}
.r-backgroundColor-x2s5ye{background-color:rgba(40,44,63,0.05);}
.r-paddingBottom-97e31f{padding-bottom:env(safe-area-inset-bottom);}
.r-paddingLeft-bv2aro{padding-left:env(safe-area-inset-left);}
.r-paddingRight-hxflta{padding-right:env(safe-area-inset-right);}
.r-paddingTop-10xqauy{padding-top:env(safe-area-inset-top);}
.r-backgroundColor-14lw9ot{background-color:rgba(255,255,255,1.00);}
.r-alignSelf-1kihuf0{-ms-flex-item-align:center;-ms-grid-row-align:center;-webkit-align-self:center;align-self:center;}
.r-flexDirection-18u37iz{-ms-flex-direction:row;-webkit-box-direction:normal;-webkit-box-orient:horizontal;-webkit-flex-direction:row;flex-direction:row;}
.r-userSelect-lrvibr{-moz-user-select:none;-ms-user-select:none;-webkit-user-select:none;user-select:none;}
.r-cursor-1loqt21{cursor:pointer;}
.r-touchAction-1otgn73{-ms-touch-action:manipulation;touch-action:manipulation;}
.r-justifyContent-1h0z5md{-ms-flex-pack:start;-webkit-box-pack:start;-webkit-justify-content:flex-start;justify-content:flex-start;}
.r-WebkitOverflowScrolling-150rngu{-webkit-overflow-scrolling:touch;}
.r-flexGrow-16y2uox{-ms-flex-positive:1;-webkit-box-flex:1;-webkit-flex-grow:1;flex-grow:1;}
.r-flexShrink-1wbh5a2{-ms-flex-negative:1;-webkit-flex-shrink:1;flex-shrink:1;}
.r-overflowX-lltvgl{overflow-x:auto;}
.r-overflowY-buy8e9{overflow-y:hidden;}
.r-transform-1sncvnh{-webkit-transform:translateZ(0px);transform:translateZ(0px);}
.r-scrollbarWidth-2eszeu::-webkit-scrollbar{display:none}
.r-scrollbarWidth-2eszeu{scrollbar-width:none;}
.r-elevation-1hpgsb4{;}
.r-marginBottom-5oul0u{margin-bottom:8px;}
.r-paddingBottom-xd6kpl{padding-bottom:8px;}
.r-paddingTop-tskmnb{padding-top:8px;}
``` 

But the html has following classes mentioned:
```html
<div class="css-view-1dbjc4n r-left-1d2f490 r-overflow-1udh08x r-pointerEvents-12vffkv r-position-u8s1d r-right-zchlnj r-top-ipm5af">
....
</div>

```

css for class ` r-top-ipm5af` is not there in genereted style.

**How to reproduce**
Using following code to generate html & css at server side:

```js
      AppRegistry.registerComponent("App", () => AppEntry);
      const { element, getStyleElement } = AppRegistry.getApplication("App", { initialProps });
      let htmlStr = ReactDOMServer.renderToString(element);
      const css = ReactDOMServer.renderToStaticMarkup(getStyleElement());
```

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.15.0  & 0.15.6 (tried with both)
* React (version): 16.9.0
* Node: v12.20.1
