### ISSUE TITLE
marginStart and marginEnd are not dynamic

### ISSUE THREAD

**Issue by TheEhsanSarshar** [necolas/react-native-web#2114]
I know that `CSS` doesn't have `marginStart` and `marginEnd` so `React-Native-Web` changes them to the marginLeft or marginRight depending on the `i18Manager.isRtl` result.
but when changing the language of the app by using `i18Manager.forceRtl(true)` those marginLeft and marginRight values are not changing. can we have a better approach internally in `react-native-web` to handle it out of the box?

if instead of converting `marginStart: 10` to `margin-left: 10px` we use this method 
```css
[dir="ltr"] p {
    margin-left: 10px
}

[dir="rtl"] p {
    margin-right: 10px
}
```
the issue will be solved
