### ISSUE TITLE
Styling component internals with CSS in v0.18

### ISSUE THREAD

**Issue by marklawlor** [necolas/react-native-web#2294]
I'm the author of a RN style preprocessor and I'd like to propose a API to improve styling component internals through known keys on a preprocessed style object.

Currently it's difficult to apply CSS styles to components like `<Switch />` as its appearance changes based upon a prop value and the color values are applied as inline styles to multiple components.

I propose that each component has a a set of known class keys that it can selectively apply to internal elements based upon the component state.

For example:

```tsx
<Switch style={{
  $$css: true.
  $$trackColor: "my-track-class",
  $$activeTrackColor: "my-active-track-class",
  $$thumbColor: "my-thumb-class",
  $$activeThumbColor: "my-thumb-class"
}} />
```

By default `<Switch />` will render as 

```tsx
<div>
  <div class="my-track-class" />
  <div class="my-thumb-class" />
</div>
```

But when `value={true}`, it removes the `$$trackColor` and `$$thumbColor` classes and replaces them with the `$$activeTrackColor` and `$$activeThumbColor` class.

```tsx
<div>
  <div class="my-active-track-class" />
  <div class="my-active-thumb-class" />
</div>
```

Each component will have its own unique set of known keys that are specific to its styling needs. The keys don't necessarily need to correspond to the components props. For example `<ActivityIndicator />` could use the known keys of

```tsx
<ActivityIndicator style={{
  $$css: true,
  $$ringBackground: "background-stroke-class",
  $$ringForeground: "foreground-stroke-class"
}}/>
```

This proposed API would greatly simplify my current method, which involves applying a base class and another active state class. For example my current method of styling `<Switch />` can be demonstrated by this simplified code example:

```css
.switch.trackColor { --track-color: <color > }
.switch.is-active.activeTrackColor { --track-color: <color > }

.switch.thumbColor { --thumb-color: <color > }
.switch.is-active.activeThumbColor { --thumb-color: <color > }

.switch:nth-child(1) { backgroundColor: var(--track-color) }
.switch:nth-child(2) { backgroundColor: var(--thumb-color) }
``` 

Each <Switch /> is wrapped in a HOC and which applies the base class `switch` and the class `is-active` when the prop `value={true}`.

I think an API like this will benefit RWN and allow easier integration for preprocessor authors.
