### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by VinceBT** [necolas/react-native-web#528]
Something during 77fd8674215c0c2bd1ea447786df4f981d08a1c8 made that now the app does not take the whole page anymore.
Version: 0.0.98 and beyond

**Comment by maszaa** [comment]
I've noticed the same thing. [Sample code](https://codepen.io/anon/pen/awdJOv?editors=0010)

**Comment by thenewvu** [comment]
Me to, I had to add this:

```css
html,body, #react-root {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
}
```
