### ISSUE TITLE
AppRegistry double wraps and sets {position:absolute}

### ISSUE THREAD

**Issue by nikhedonia** [necolas/react-native-web#871]
Currently we at https://thetimes.co.uk cannot embed our RNW-app at into our website as it wraps our component with a `<div style={{position:"absolute", ...}><div> ... </div></div>`.

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/AppRegistry/AppContainer.js#L49

Can we get rid of at least the absoluteFill?

cheers.

**Comment by grit96** [comment]
Is there any way for me to apply the absolute fill to the container through a prop now it's been removed?

**Comment by grit96** [comment]
It is possible to achieve it now by adding the following styles to the root container:

```css
      #root {
        position: absolute;
        display: flex;
        width: 100%;
        height: 100%;
      }
```
